javascript-loops - Lamberto Martinez
Lambpato/c0123-code-solutions pull request #33
Opened 2023-02-02 00:20 UTC by Lambpato

![Screenshot 2023-02-01 at 4 20 04 PM](https://user-images.githubusercontent.com/34325124/216199699-b606be12-09ac-41f9-b8d4-8faa1f6899ca.png)

2023-02-02 17:21 UTC, shawnkost requested changes
A few changes requested here Lamberto!

2023-02-02 17:21 UTC, shawnkost commented on javascript-loops/main.js
> +  var currentNumber = 0;
This should be 1

2023-02-02 17:21 UTC, shawnkost commented on javascript-loops/main.js
> +  while (currentNumber < 10) {
This should be less than or equal to. We want to include 10

2023-02-02 17:21 UTC, shawnkost commented on javascript-loops/main.js
> +  var currentNumber = 0;
This should be 2

2023-02-02 17:21 UTC, shawnkost commented on javascript-loops/main.js
> +  while (currentNumber < 20) {
This should be less than or equal to. We want to include 20

2023-02-03 17:02 UTC, JenBowman1 approved these changes
👍

2023-02-03 17:03 UTC, merged