css-transitions -Lamberto Martinez
Lambpato/c0123-code-solutions pull request #46
Opened 2023-02-08 02:38 UTC by Lambpato

2023-02-08 22:02 UTC, shawnkost requested changes
A few changes requested here, Lamberto! Please make sure to include a screenshot of the completed exercise

2023-02-09 00:10 UTC, JenBowman1 requested changes
just one small change!

2023-02-09 00:10 UTC, JenBowman1 commented on css-transitions/styles.css
> +  transition: all 0.5s;
hi Lamberto, as Shawn mentioned, please don't apply transition properties to pseudo selectors!

2023-02-09 05:22 UTC, Lambpato commented
https://user-images.githubusercontent.com/34325124/217725205-13948a8f-0e19-413a-8b0b-677ce0e6e417.mov

2023-02-09 16:43 UTC, shawnkost approved these changes
👍🏻

2023-02-09 17:52 UTC, merged